const USER = [
  {
    userId: 1,
    name: '김관리',
    email: 'admin@example.com',
    role: 'ROLE_ADMIN',
    reportCount: 0,
    isDeactivate: false,
    deactivateCount: 1,
  },
  {
    userId: 2,
    name: '이철수',
    email: 'ironman@example.com',
    role: 'ROLE_USER',
    reportCount: 2,
    isDeactivate: false,
    deactivateCount: 0,
  },
  {
    userId: 3,
    name: '박영희',
    email: 'younghee@example.com',
    role: 'ROLE_USER',
    reportCount: 0,
    isDeactivate: false,
    deactivateCount: 3,
  },
  {
    userId: 4,
    name: '최민수',
    email: 'minsu@example.com',
    role: 'ROLE_USER',
    reportCount: 5,
    isDeactivate: true,
    deactivateCount: 1,
  },
  {
    userId: 5,
    name: '정다은',
    email: 'daeun@example.com',
    role: 'ROLE_USER',
    reportCount: 1,
    isDeactivate: false,
    deactivateCount: 0,
  },
  {
    userId: 6,
    name: '강지훈',
    email: 'jihun@example.com',
    role: 'ROLE_USER',
    reportCount: 3,
    isDeactivate: false,
    deactivateCount: 0,
  },
  {
    userId: 7,
    name: '윤서연',
    email: 'seoyeon@example.com',
    role: 'ROLE_USER',
    reportCount: 0,
    isDeactivate: false,
    deactivateCount: 0,
  },
  {
    userId: 8,
    name: '장현우',
    email: 'hyunwoo@example.com',
    role: 'ROLE_USER',
    reportCount: 4,
    isDeactivate: true,
    deactivateCount: 0,
  },
  {
    userId: 9,
    name: '임수진',
    email: 'sujin@example.com',
    role: 'ROLE_USER',
    reportCount: 1,
    isDeactivate: false,
    deactivateCount: 0,
  },
  {
    userId: 10,
    name: '한지민',
    email: 'jimin@example.com',
    role: 'ROLE_USER',
    reportCount: 0,
    isDeactivate: false,
    deactivateCount: 0,
  },
];

export default USER;
